### ISSUE TITLE
Three or more ANDs in WHERE clause fails parsing

### ISSUE THREAD

**Issue by scotty-g** [jksy/sql_parser#16]
Tested with ruby-2.4 and 2.3. oracle-sql-parser-0.9.0. When three or more `AND` operators are added to a WHERE clause the parser fails.

This is successful:
```ruby
sql = "select f1,f2,f3 from t1 where f1 = '?' and f2 ='?'"
syntax_tree = parser.parse sql
```

This returns nil:
```ruby
sql ="select f1,f2,f3 from t1 where f1 = '?' and f2 ='?' and f3 = '?'"
syntax_tree = parser.parse sql
```
`parser.failure_reason` is nil as well.

**Comment by jksy** [comment]
@scotty-g 
Sorry for reply late.
I'll check and reply.

**Comment by jksy** [comment]
@scotty-g 
I fixed it.
Please use version 0.9.1.
I am very grateful for your report. Thank you very much.
